version: "3.7"
services:
  db:
    image: mysql_env
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: whdgns1002@
    extra_hosts:
    - "host.docker.internal:host-gateway"
  tomcat:
    image: tomcat_env
    build:
      context: .
      dockerfile: Dockerfile-tomcat
    ports:
      - "8080:8080"
    links:
      - db
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always