apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mysql
spec:
  selector:
    matchLabels:
      app: mysql
    strategy:
      type: recreate
    template:
      metadata:
        labels:
          app: mysql
      spec:
        nodeSelector:
          topology.kubernetes.io/zone: us-central1-a
        containers:
        - image: mysql:5.7.8
          name: mysql
          env:
          - name:_MYSQL_ROOT_PASSWORD
            valueFrom:
              secretKeyRef:
                name: mysql-credential
                key: password
          - name: MYSQL_DATABASE
            value: petclinic
          ports:
          - containerPort: 3306
            name: mysql
          volumeMounts:
          - name: mysql-persistent-storage
            mountPath: /var/lib/mysql
       volumes:
       - name: mysql-persistent-storage
         persistentVolumeClaim: 
           claimName: mysql-pv-claim
